services:
  mysql:
    image: mysql:latest
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: spring
    healthcheck:
      test: mysqladmin ping -u root -p $$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #    image: zero-kilometer/spring:v1
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: