app:
  ffmpeg:
    ffmpeg: /usr/bin/ffmpeg
    ffprobe: /usr/bin/ffprobe
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/road_of_memory
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        type:
          preferred_uuid_jdbc_type: CHAR
