openapi: 3.0.1
info:
  title: User Authentication API
  description: REST API для авторизации и обновления токенов пользователей.
  version: 1.0.0

paths:
  /auth:
    post:
      summary: Авторизация пользователя
      description: Проверяет данные пользователя и выдает JWT access/refresh токены.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuthDto'
      responses:
        '200':
          description: Токены успешно сгенерированы
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '400':
          description: Некорректные данные пользователя
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                type: string

  /refresh:
    post:
      summary: Обновление токена
      description: Обновление JWT access токена по refresh токену
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenDto'
      responses:
        '200':
          description: Токен успешно обновлен
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '400':
          description: Некорректный refresh токен
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    UserAuthDto:
      type: object
      required:
        - id
        - first_name
        - auth_date
        - hash
      properties:
        id:
          type: integer
          example: 123456
        first_name:
          type: string
          example: Иван
        last_name:
          type: string
          example: Иванов
        username:
          type: string
          example: ivan123
        photo_url:
          type: string
          example: https://example.com/photo.jpg
        auth_date:
          type: integer
          example: 1672500000
        hash:
          type: string
          example: "securehashvalue"

    RefreshTokenDto:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
